openapi: 3.0.3
info:
  title: Onboarding API 
  version: '1.2'
  description: STD22050
  contact:
    email: hei.ando.1007@gmail.com
servers:
  - url: http://STD22050.com
  
paths:
  /students:
    get:
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                - id: 1
                  name: ando
                  birthdate: 2023-01-01 
                - id: 2
                  name: kira
                  birthdate: 2023-01-01 
    post:
      summary: Add a new student
      operationId: addStudent
      requestBody:
        description: Student object to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  type: string
              example:
                id: 3
                name: rakoto 
                email: 2000-01-01 
      responses:
        '201':
          description: Student added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 3
                  name:
                    type: string
                    example: ramanantsoa
                  birthdate:
                    type: string
                    example: 2000-01-01